// lib/photoData.ts

export const photoData = [
  {
    mainCategory: "Karate",
    subcategories: [
      {
        title: "Karate",
        photos: [
          // Hier fügst du für jedes Bild eine Zeile mit src und description ein:
          { src: "/fotos/karate/karate/11_2019_scb_jukuren.jpg", description: "11/2019 SCB Jukuren gratulieren" },
          { src: "/fotos/karate/karate/11_2019_scb_pruefung_2_dan.jpg", description: "11/2019 Sechs SCB-Karateka bestehen die Prüfung zum 2. Dan" },
          { src: "/fotos/karate/karate/11_2019_jkd_cup_sachsen_anhalt.jpg", description: "11/2019 JKD Cup in Sachsen Anhalt" },
          { src: "/fotos/karate/karate/11_2019_shotokan_cup_berlin.jpg", description: "11/2019 Shotokan Cup Berlin" },
          { src: "/fotos/karate/karate/12_2019_kazoku_cup_berlin.jpg", description: "12/2019 Kazoku Cup Berlin" },
          { src: "/fotos/karate/karate/1985_training-_mit_genossen_aus_vietnam.jpg", description: "1985 Training mit Genossen aus Vietnam" },
          { src: "/fotos/karate/karate/boy_san_jka_champion_kata_2009-min.jpg", description: "Boy-San (SCB) bei den JKA Championships / Tokyo 2009 - Kata" },
          { src: "/fotos/karate/karate/boy_san_jka_champion_kumite_2009-min.jpg", description: "Boy-San (SCB) bei den JKA Championships / Tokyo 2009 - Kumite" },
          { src: "/fotos/karate/karate/budo-min.jpg", description: "12/2001 BUDO-Demonstration in ausverkaufter Halle / SCB-Turngala im Sportforum" },
          { src: "/fotos/karate/karate/davos-min.jpg", description: "10/2004 als Teilnehmer an der ITKF-WM in Davos/CH" },
          { src: "/fotos/karate/karate/dsc01147-min.jpg", description: "Dojo im ehemaligen WR F.E.D." },
          { src: "/fotos/karate/karate/fujinaga_leipzig-min.jpg", description: "1994 in Leipzig mit Fujinaga Sensei" },
          { src: "/fotos/karate/karate/hart_aber_herzlich-min.jpg", description: "mit Kevin & Nathan - hart aber herzlich" },
          { src: "/fotos/karate/karate/jkd-cup_2011-min.jpg", description: "JKD Cup 2011" },
          { src: "/fotos/karate/karate/l_hkr_juni_2012-min.jpg", description: "Hauptkampfrichter Juni 2012" },
          { src: "/fotos/karate/karate/lg_frank_pelny_sep_2012-min.jpg", description: "Lehrgang mit Frank Penly September 2012" },
          { src: "/fotos/karate/karate/nach_dan_pruefung-min.jpg", description: "08/2006 nach der bestandenen Dan-Prüfung" },
          { src: "/fotos/karate/karate/nishiyama_berlin_2003-min.jpg", description: "Nishiyama Sensei in Berlin 2003" },
          { src: "/fotos/karate/karate/ochi_lg-min.jpg", description: "04/2007 beim Oster-LG mit Sensei Ochi in Alt-Meteln" },
          { src: "/fotos/karate/karate/offene_srd_meisterschaft_2011-min.jpg", description: "offene SRD Meisterschaft 2011" },
          { src: "/fotos/karate/karate/orangegurtpruefung-min.jpg", description: "22. Juni 2009 / Nach bestandener Orangegurtprüfung" },
          { src: "/fotos/karate/karate/scb_senioren-min.jpg", description: "17. Juni 2009 / 15. Geburtstag unserer SCB-Senioren-SV-Gruppe" },
          { src: "/fotos/karate/karate/scb_team_ungarn-min.jpg", description: "SCB-Team in Ungarn" },
          { src: "/fotos/karate/karate/skdun_welt-cup_2011-min.jpg", description: "1. Platz SKDUN Welt Cup 10/2011" },
          { src: "/fotos/karate/karate/tl_zinnowitz_2006-min.jpg", description: "04/2006 SCB-Trainingslager in Zinnowitz/Ostsee" },
          { src: "/fotos/karate/karate/toshiyuki_fujinaga_berlin-min.jpg", description: "Toshiyuki Fujinaga in Berlin" },
          { src: "/fotos/karate/karate/us-team_im_sportforum-min.jpg", description: "US-Team im Sportforum" },
          { src: "/fotos/karate/karate/wiedersehen-min.jpg", description: "Ein Wiedersehen" },
          { src: "/fotos/karate/karate/wm_bronze-min.jpg", description: "10/2005 WM-Bronze mit Philip Grahl und Jens Voigt" },
          { src: "/fotos/karate/karate/zinnowitz_2007-min.jpg", description: "04/2007 im SCB-Trainingslager Zinnowitz/Ostsee" },
          { src: "/fotos/karate/karate/IMG-20180704-WA0000.jpg", description: "05/2018 Naka Sensei in Berlin" },
          { src: "/fotos/karate/karate/IMG-20180704-WA0002.jpg", description: "Die Adlershofer Schlümpfe" },
          { src: "/fotos/karate/karate/IMG-20180704-WA0001.jpg", description: "JKD Gasshuku in Berlin" },
          { src: "/fotos/karate/karate/IMG-20180704-WA0003.jpg", description: "Zeichnen / nur ein Hobby" },
          { src: "/fotos/karate/karate/IMG-20180704-WA0004.jpg", description: "Die richtigen Adlershofer" },
          { src: "/fotos/karate/karate/IMG-20180704-WA0021.jpg", description: "04/2017 Blick aus dem Dojo: Kirschbluete im Dynamo Sportforum Hohenschönhausen." },
          { src: "/fotos/karate/karate/kokubun_2018_1.jpg", description: "10/2018 Mit Kokubun Sensei und Mario Lübke in Schwerin" },
          { src: "/fotos/karate/karate/dkv_a_pruefung_2018_1.jpg", description: "11/2018 Erfolgreich als DKV-A-PRÜFER mit Frank Herrmann (JKD Bundesstilrichtungsreferent) in Berlin" },
          { src: "/fotos/karate/karate/IMG-20190615-WA0003.jpg", description: "06/2019 JKD-Gasshuku Berlin" },
          { src: "/fotos/karate/karate/IMG-20220426-WA0004.jpg", description: "2023 ... ist schon in Sicht!!!" },
          { src: "/fotos/karate/karate/IMG-20220426-WA0003.jpg", description: "Für die Party nach dem anstrengenden Training: Danke Franzi!" },
          { src: "/fotos/karate/karate/IMG-20220426-WA0002.jpg", description: "04/2022 Mit Abteilungsleiter Judo/Karate im SC berlin: Sportsfreund Julien Tieke" },
          { src: "/fotos/karate/karate/IMG-20220426-WA0001.jpg", description: "04/2022 Osteseeluft ist so gesund!" },
          { src: "/fotos/karate/karate/IMG-20220426-WA0000.jpg", description: "Nach 2 Jahren \"Corona\"-Pause: 04/2022 ...endlich wieder ein SCB-Trainingslager in der Sportschule Zinnowitz" },
          { src: "/fotos/karate/karate/IMG-20210117-WA0011.jpg", description: "Mit David Herascu, Mein erster Dan Absolvent Crystal Palace 05/1997" },
          { src: "/fotos/karate/karate/IMG-20220901-WA0000.jpg", description: "SCB Trainingslager Ruhlsdorf 07/2022" },
          { src: "/fotos/karate/karate/IMG-20230818-WA0000.jpg", description: "SCB-Trainingslager Zinnowitz 04/2023" },  
          { src: "/fotos/karate/karate/IMG-20230818-WA0001.jpg", description: "JKD-Gasshuku mit Kokubun-Sensei in Berlin 05/2023" },
          { src: "/fotos/karate/karate/IMG-20230818-WA0002.jpg", description: "SCB-Sommer-Camp Ruhlsdorf 08/2023" },   
          { src: "/fotos/karate/karate/JKD_Dan_Pruefung_11_2022.jpg", description: "11/2022 Gemeinsam... Fair... Erfolgreich. Dan-Prüfungen in der Bundesstilrichtung JKD in Berlin." },
          { src: "/fotos/karate/karate/IMG-20231127-WA0000.jpg", description: "11/2023 Als Gasttrainer beim USV Jena" },
          { src: "/fotos/karate/karate/IMG-20231127-WA0002.jpg", description: "11/2023 Erfolgreiche Arbeit als DKV-A-Prüfer mit Christopher Krähnert " },
          { src: "/fotos/karate/karate/1986_University.jpg", description: "Sommer 1986 / im Universitäts-Dojo" },
          { src: "/fotos/karate/karate/1988_Embu_Bodensee.jpg", description: "1988 / Embu am Bogensee" },
          { src: "/fotos/karate/karate/1993_shodan_london.jpg", description: "Mai 1993 / kurz vor der Shodan-Prüfung im Crystal Palace (London)" },
          { src: "/fotos/karate/karate/JKD_Sommerlager_2024.jpg", description: "06/2024 JKD Sommerlager in Berlin" },
          { src: "/fotos/karate/karate/JKD_Sommerlager_Team_2024.jpg", description: "06/2024 Trainier-Team beim JKD Sommerlager in Berlin" },  
          { src: "/fotos/karate/karate/wiedersehen_2024.jpg", description: "06/2024 Wiedersehen mit Beate. Sie war Sempai im Dojo Adlershof/DDR" },   
          { src: "/fotos/karate/karate/IMG-20240714-WA0000.jpg", description: "06/2024 Fujinaga-Schüler aus Berlin und Leipzig nach dem Lehrgang mit Nemoto-Sensei" },
          { src: "/fotos/karate/karate/2024-TL-Ruhlsdorf-Gruppenfoto_v2.jpg", description: "08/2024 SCB-Trainingslager Ruhlsdorf" },   
          { src: "/fotos/karate/karate/IMG-20240912-WA0002.jpg", description: "09/2024 - SC Berlin e.V. Karate-Dojo Lichtenberg" },
          { src: "/fotos/karate/karate/2024_Pruefungskommissision.jpg", description: "11/2024 Mit Kokubun Sensei und Helge W. in der KKV-Prüfungskommission für Christopher K. zum 6.Dan" },
          { src: "/fotos/karate/karate/2024_Kazoku-Cup.jpg", description: "12/2024 Ein strakes Team des SC Berlin e.V. beim Kazoku-Cup in Höhenschonhausen" },
          { src: "/fotos/karate/karate/2024_DKV-Pruefung-scaled.jpg", description: "11/2024 Traditionell erfolgreich Mit Frank Herrmann als DKV-A-Prüfer in Berlin" },
          { src: "/fotos/karate/karate/auszeichnung_BKV.jpg", description: "03/2025 Eine besondere Auszeichnung vom Berliner Karate Verband" },
          { src: "/fotos/karate/karate/2025_04_zinnowitz-scaled.jpg", description: "04/2025 SCB-Ostseee Trainingslager Zinnowitz" },
          { src: "/fotos/karate/karate/geschenk_2025.jpg", description: "08/2025 Geschenk von den Karateka des SC Berlin e.V." },
          { src: "/fotos/karate/karate/giants_cheeleader_ruhlsdorf_2025.jpg", description: "Foto-Termin min den GIANTS Cheeleader aus Berlin in Ruhlsdorf" },
          { src: "/fotos/karate/karate/jkd_gasshuku_2025.jpg", description: "07/2025 JKD-Gasshuku mit Iwamoto-Sensei in Schwerin" },
          { src: "/fotos/karate/karate/trainingslager_ruhlsdorf_2025.jpg", description: "08/2025 SCB-Sommer-Trainingslager im Feriendorf Dorado/Ruhlsdorf" },
          { src: "/fotos/karate/karate/hashimoto_2025.jpg", description: "13./14. September 2025 Lehrgang mit Hashimoto, Kenji (6.Dan) in Berlin" },
          { src: "/fotos/karate/karate/1_berliner_team_katae_cup_2025.jpg", description: "1. Berliner Team Kata Cup 2025 (11.10.) SC Berlin e.V., 14 Teams, 11 Medailienplätze" },
          { src: "/fotos/karate/karate/1_berliner_team_katae_cup_2025_2.jpg", description: "1. Berliner Team Kata Cup 2025 Sieger in der Oberstube. Hung Nguyen Duc (4. Dan), Konstantin Skudler (3. Dan), Alexander Skudler (1.Dan) Meisterschüler!!!" },
          { src: "/fotos/karate/karate/1_berliner_team_katae_cup_2025_3.jpg", description: "1. Berliner Team Kata Cup 2025 Älteste Teilnehmer aus der SCB Morning Class, Heinz Rygoll (85 J.), Peter Krol (70 J.), Diethard Heyer (81 J.) v.l.n.r Silbermedaile" },
          { src: "/fotos/karate/karate/JKD_Pruefung_11_2025.jpg", description: "JKD Prüfungs- und Jubiläumslehrgang 20 Jahre Karate im Berliner TSC 11/2025" }
        ]
      },
      { 
        title: "SCB-Pfingst-LG mit Seto-Sensei",
        photos: [
          { src: "/fotos/karate/pfingsten/dsc00063-min.jpg", description: "Japanische Gäste im Sportforum" },
          { src: "/fotos/karate/pfingsten/dsc00067-min.jpg", description: "Gruppenfoto mit Gästen" },
          { src: "/fotos/karate/pfingsten/fj_seto_2008_klein-min.jpg", description: "Trainer - Kollegen" }
        ]
      },
      {
        title: "Otake Sensei in Schwerin - 2012",
        photos: [
          { src: "/fotos/karate/otake/schwerin_danpruefung-min.jpg", description: "Bestandene Dan-Prüfung" },
          { src: "/fotos/karate/otake/schwerin_otake_2012-min.jpg", description: "Teilnehmer beim Lehrgang" },
          { src: "/fotos/karate/otake/schwerin_puerfungskommission-min.jpg", description: "Dan-Prüfungskommission" }
        ] // Hier später deine Bilder einfügen
      },
      { title: "Budapest 2010", photos: [
          { src: "/fotos/karate/budapest/19_budapest-min.jpg", description: "Budapest" },   
          { src: "/fotos/karate/budapest/20_jka-trainer-min.jpg", description: "JKA-Trainer" },
          { src: "/fotos/karate/budapest/21_mit-naito-sensei-min.jpg", description: "mit Naito-Sensei" },
          { src: "/fotos/karate/budapest/22_mit-sawada-sensei-min.jpg", description: "mit Sawada-Sensei" }
      ] },
      { title: "USA Reise 2010", photos: [
          { src: "/fotos/karate/usa/1_abflug-txl-min.jpg", description: "Abflug TXL" },
          { src: "/fotos/karate/usa/2_universal-studios-min.jpg", description: "Universal Studios" },
          { src: "/fotos/karate/usa/3_hollywood-min.jpg", description: "Hollywood" },
          { src: "/fotos/karate/usa/4_action-pur-min.jpg", description: "Action Pur" },
          { src: "/fotos/karate/usa/5_camp-shotokan-min.jpg", description: "AJKA-Camp SHOTOKAN 08/2010" },
          { src: "/fotos/karate/usa/6_medaillenausbeute-min.jpg", description: "SCB-Medaillengewinner" },
          { src: "/fotos/karate/usa/7_just-for-fun-min.jpg", description: "Just for Fun" },
          { src: "/fotos/karate/usa/8_mit-sensei-yabe-min.jpg", description: "mit Sensei Yabe" },
          { src: "/fotos/karate/usa/9_scb-power-kick-min.jpg", description: "SCB-Power Kick" },
          { src: "/fotos/karate/usa/10_mit-schwung-min.jpg", description: "mit Schwung" },
          { src: "/fotos/karate/usa/11_und-sprung-min.jpg", description: "Und Sprung" },
          { src: "/fotos/karate/usa/12_unterwegs-min.jpg", description: "Unterwegs" },
          { src: "/fotos/karate/usa/13_grand-canyon-ranch-min.jpg", description: "Grand Canyon Ranch" },
          { src: "/fotos/karate/usa/14_las-vegas-min.jpg", description: "Las Vegas" },
          { src: "/fotos/karate/usa/15_bei-hooters-min.jpg", description: "Bei Hooters" },
          { src: "/fotos/karate/usa/16_am-venice-beach-min.jpg", description: "Am Venice Beach" }
      ] },
      { title: "AJKA-EuroCup 2008", photos: [
        { src: "/fotos/karate/ajkaeurocup/100_0482-min.jpg", description: "1. Platz Team Kata" },
        { src: "/fotos/karate/ajkaeurocup/100_0498-min.jpg", description: "2. Platz Kata AKL ü. 35" },
        { src: "/fotos/karate/ajkaeurocup/100_0508-min.jpg", description: "mit dem SRD-Team" }
              ] },
      { title: "WUKO-EM / Belgien", photos: [
        { src: "/fotos/karate/wuko/230508-091606-min.jpg", description: "WUKO-EM / Belgien" },
        { src: "/fotos/karate/wuko/dsc00729-min.jpg", description: "Coach und Kämpfer" }
      ] }
    ]
  },
  {
    mainCategory: "Japan",
    subcategories: [
      { 
        title: "Japan 2006", 
        photos: [
          { src: "/fotos/japan/2006/100_0442-min.jpg", description: "Abendessen nach dem Training mit Seto-Sensei" },
          { src: "/fotos/japan/2006/100_0446-min.jpg", description: "am Grab der Familie Fujinaga / 15.10.2006" },
          { src: "/fotos/japan/2006/dscf0055-min.jpg", description: "als Samurai in Nikko" },
          { src: "/fotos/japan/2006/dscf0057-min.jpg", description: "mit \"Freund und Helfer\" in Nikko" }, 
          { src: "/fotos/japan/2006/japan_079-min.jpg", description: "Gruppenfoto mit Seto-Sensei / Tokyo 10/2006" },
          { src: "/fotos/japan/2006/japan_183-min.jpg", description: "am Grab der Familie Fujinaga / 15.10.2006" },
          { src: "/fotos/japan/2006/japan2_029-min.jpg", description: "im JKA-Honbu-Dojo mit Peggy F." }, 
          { src: "/fotos/japan/2006/japan2_433-min.jpg", description: "in der Burg Himeji" },
          { src: "/fotos/japan/2006/japan2_482-min.jpg", description: "auf MIYAJIMA" }
        ] 
      },
      { title: "Japan 04/2009", photos: [
          { src: "/fotos/japan/2009/100_1512-min.jpg", description: "Auf dem Weg nach TSUMAGO: Kirschblüten Tricolor" },
          { src: "/fotos/japan/2009/100_1527-min.jpg", description: "Abendessen im RYOKAN \"DAI KICHI\"" },
          { src: "/fotos/japan/2009/100_1595-min.jpg", description: "Frühling auf MIYAJIMA" },
          { src: "/fotos/japan/2009/100_1598-min.jpg", description: "Immer wieder schön: Das Tor" },
          { src: "/fotos/japan/2009/100_1695-min.jpg", description: "Die Brücke von IWAKUNI" },
          { src: "/fotos/japan/2009/dsc00298_1-min.jpg", description: "\"Wochenend-Dojo\" in NARA: schön wärs." },
          { src: "/fotos/japan/2009/dscf0584-min.jpg", description: "Besuch der Schwertschmiede in OSAFUNE (inkl. Schwertmuseum und Shop)" },
          { src: "/fotos/japan/2009/dscf0613-min.jpg", description: "Die schwarze Burg von OKAYAMA)" },
          { src: "/fotos/japan/2009/seto_dojo-min.jpg", description: "09.04.2009, Seto-Sensei bat mich um eine Lehrprobe. Es war mir eine große Ehre!" },
          { src: "/fotos/japan/2009/siggis-fotos-183-min.jpg", description: "\"INTERNATIONAL BLACK JACKET TEAM\" in KAMAKURA" }
      ] },
      { title: "Japan 04/2015", photos: [
        { src: "/fotos/japan/2015/abendessen_im_ryokan-min.jpg", description: "Abendessen im Ryokan" },
        { src: "/fotos/japan/2015/als_gaeste_im_setojuku_dojo-min.jpg", description: "Als Gäste im Setojuku-Dojo" },
        { src: "/fotos/japan/2015/auf_dem_weg_nach_tsumago-min.jpg", description: "Auf dem Weg nach Tsumago" },
        { src: "/fotos/japan/2015/fuer_die_kamera_zu_schnell-min.jpg", description: "Für die Kamera zu schnell" },  
        { src: "/fotos/japan/2015/im_kloster_koyasan-min.jpg", description: "Im Kloster Koyasan" },
        { src: "/fotos/japan/2015/in_matsumoto-min.jpg", description: "In Matsumoto" },
        { src: "/fotos/japan/2015/in_nara-min.jpg", description: "In Nara" },
        { src: "/fotos/japan/2015/in_osaka-min.jpg", description: "In Osaka" },
        { src: "/fotos/japan/2015/jka_friends_mit_seto_sensei-min.jpg", description: "JKA-Friends mit Seto Sensei" },
        { src: "/fotos/japan/2015/kenjutsu_training_in_osaka-min.jpg", description: "Kenjutsu-Training in Osaka" },
        { src: "/fotos/japan/2015/kumite_training-min.jpg", description: "Kumite-Training" },
        { src: "/fotos/japan/2015/scb_reisegruppe_2015-min.jpg", description: "SCB Reisegruppe 2015" },
        { src: "/fotos/japan/2015/spass_muss_sein_im_bambushain-min.jpg", description: "Spaß muss sein im Bambushain" },
        { src: "/fotos/japan/2015/training_einmal_anders-min.jpg", description: "Training einmal anders" },
        { src: "/fotos/japan/2015/unterstuetzung_beim_jion_training-min.jpg", description: "Unterstützung beim Jion-Training" }
      ] }
    ]
  },
  {
    mainCategory: "Weitere Bilder",
    subcategories: [
      { title: "Weitere Fotos", photos: [
          { src: "/fotos/sonstiges/12_2019_Bogenschiessen.jpg", description: "12/2019 Mal was Anderes: Bogenschiessen im Olympiastützpunkt Berlin" },
          { src: "/fotos/sonstiges/8_mai_2020.jpg", description: "08. Mai 2020 / Feiertag in Berlin" },
          { src: "/fotos/sonstiges/17_ps-training-min.jpg", description: "PS-Training / Kallinchen" },
          { src: "/fotos/sonstiges/18_reinsdorf_2010-min.jpg", description: "Reinsdorf 08/2010" },
          { src: "/fotos/sonstiges/23_boot-min.jpg", description: "Absetzübung 06/2010" },
          { src: "/fotos/sonstiges/24_jka_training_camp-min.jpg", description: "Budapest - JKA Certificate" },
          { src: "/fotos/sonstiges/cottbus_2008-min.jpg", description: "Cottbus 08/2008" },
          { src: "/fotos/sonstiges/ein_maennertraum-min.jpg", description: "Ein Männertraum" },
          { src: "/fotos/sonstiges/fit_mit_44a-min.jpg", description: "07/2007 als Veteran der Anti-Terror-Einheit zu Gast beim HKX der NVA-Fallschirmjäger/ fit mit 44...beim Aufwärmtraining" },
          { src: "/fotos/sonstiges/fjtv_hkx-min.jpg", description: "06/2009 Mit Kameraden des FJTV-Ost e.V. beim HKX in Lehnin" },
          { src: "/fotos/sonstiges/gute_kameraden-min.jpg", description: "Gute Kameraden" },
          { src: "/fotos/sonstiges/IMG_3291-min.jpg", description: "Ehrensache(n)!" },
          { src: "/fotos/sonstiges/immer_bereit-min.jpg", description: "... Immer bereit!!!" },
          { src: "/fotos/sonstiges/keri_waza-min.jpg", description: "Wochenend-Kurs zum \"Wunsch-Thema\"" },
          { src: "/fotos/sonstiges/minister_a_d-min.jpeg", description: "Minister a.D. und Personenschützer a.D." },
          { src: "/fotos/sonstiges/soldat_1-min.jpg", description: "als Gruppenführer im SEK 02/1991" },
          { src: "/fotos/sonstiges/spezialistentreffen_ost_west-min.jpg", description: "Spezialistentreffen Ost/West" },
          { src: "/fotos/sonstiges/tierische_reunde-min.jpg", description: "tierische Feunde" },
          { src: "/fotos/sonstiges/u_jitsu_seminar_mai_2009-min.jpg", description: "International Ju-Jitsu-Seminar" },
          { src: "/fotos/sonstiges/waffenbrueder_2016-min.jpg", description: "Waffenbrüder 2016" },
          { src: "/fotos/sonstiges/agm_s_de_ix-min.jpg", description: "AGM/S und DE/IX in der Schweiz" },
          { src: "/fotos/sonstiges/korea_1-min.jpg", description: "als Offizier der Anti-Terror-Einheit in Nord-Korea 07/1989" },
          { src: "/fotos/sonstiges/IMG-20180704-WA0005.jpg", description: "06/2018 SG DYNAMO trifft SC DYNAMO" },
          { src: "/fotos/sonstiges/IMG-20180704-WA0006.jpg", description: "Veteranen auf Tour" },
          { src: "/fotos/sonstiges/IMG-20180704-WA0015.jpg", description: "06/2018 Berlin ist schön." },
          { src: "/fotos/sonstiges/IMG-20180704-WA0016.jpg", description: "Mit Enkel \"Nr. 1\"" },
          { src: "/fotos/sonstiges/IMG-20180704-WA0017.jpg", description: "05/2018 Bei \"unserer\" Maschine" },
          { src: "/fotos/sonstiges/IMG-20180704-WA0018.jpg", description: "Schön \"lautlos\" ..." },
          { src: "/fotos/sonstiges/IMG-20180704-WA0019.jpg", description: "Geschichte ist lebendig." },
          { src: "/fotos/sonstiges/IMG-20180704-WA0020.jpg", description: "06/2017 \"Alte\" Vorbilder und Freunde ... Und immer noch fit." },
          { src: "/fotos/sonstiges/IMG-20190601-WA0005.jpg", description: "Aus der Heimat" },
          { src: "/fotos/sonstiges/IMG-20190601-WA0006.jpg", description: "Das kleine Besteck" },
          { src: "/fotos/sonstiges/IMG-20190601-WA0007.jpg", description: "Geschenk aus Moskau" },
          { src: "/fotos/sonstiges/07_89_cuba.jpg", description: "07/89 Cuba" },
          { src: "/fotos/sonstiges/07_89_cuba_2.jpg", description: "07/89 Cuba" },
          { src: "/fotos/sonstiges/es_ist_lange_her.jpg", description: "Es ist lange her..." },
          { src: "/fotos/sonstiges/man_denkt_an_uns.jpg", description: "Man denkt an uns." },
          { src: "/fotos/sonstiges/eiscafe_ruhlsdorf.jpg", description: "Tradition im Eiscafe Ruhlsdorf" },
          { src: "/fotos/sonstiges/gelebte_tradition.jpg", description: "Gelebte Tradition" },
          { src: "/fotos/sonstiges/kletterwald_09_2020.jpg", description: "09/2020 Mal was Anderes/SCB-Trainier im Kletterwald" },
          { src: "/fotos/sonstiges/souvenier_aus_moskau.jpg", description: "Souvenier aus Moskau" },
          { src: "/fotos/sonstiges/souvenier_aus_tokyo.jpg", description: "Souvenier aus Tokyo" },
          { src: "/fotos/sonstiges/souvenier_aus_yokohama.jpg", description: "Souvenier aus Yokohama" },
          { src: "/fotos/sonstiges/east_german_survival_kit.jpg", description: "04/2020 East-German Survival-Kit" },
          { src: "/fotos/sonstiges/altes_werkzeug.jpg", description: "Altes Werkzeug" },
          { src: "/fotos/sonstiges/zwei_deutsche.jpg", description: "Zwei Deutsche" },
          { src: "/fotos/sonstiges/drushba_freundschaft.jpg", description: "Drushba-Freundschaft" },
          { src: "/fotos/sonstiges/zur_erinnerung.jpg", description: "Zur Erinnerung" },
          { src: "/fotos/sonstiges/contemporary_japanese_sword.jpg", description: "Contemporary Japanese Sword" },
          { src: "/fotos/sonstiges/IMG-20220727-WA0003.jpg", description: "Special Training im ehemaligen \"DO76\"" },
          { src: "/fotos/sonstiges/IMG-20220901-WA0001.jpg", description: "SKAT ...geistiges Training am Abend/Glück gehört dazu" },
          { src: "/fotos/sonstiges/IMG-20220901-WA0002.jpg", description: "Special Edition 2022" },
          { src: "/fotos/sonstiges/IMG-20220901-WA0003.jpg", description: "Schönes Wetter, Hohe Bälle, Kurze Wege" },
          { src: "/fotos/sonstiges/IMG-20221016-WA0005.jpg", description: "" },
          { src: "/fotos/sonstiges/IMG-20221016-WA0004.jpg", description: "" },
          { src: "/fotos/sonstiges/IMG-20230818-WA0003.jpg", description: "Tradition am Eiscaffee Ruhlsdorf" },
          { src: "/fotos/sonstiges/IMG-20230818-WA0004.jpg", description: "Einfach nur Glück ... beim Feierabend-Skat" },
          { src: "/fotos/sonstiges/IMG-20231127-WA0001.jpg", description: "11/2023 Geschenke aus Jena" },
          { src: "/fotos/sonstiges/IMG-20240714-WA0003.jpg", description: "07/2024 Offiziere am alten \"Dienstobjekt\" ... Jetzt in Cottbus" },
          { src: "/fotos/sonstiges/IMG-20240714-WA0002.jpg", description: "07/2024 Innenansicht unserer alten \"Sporthalle\"" },
          { src: "/fotos/sonstiges/IMG-20240714-WA0001.jpg", description: "07/2024 Kameraden beim Flugplatzfest in Cottbus" },
          { src: "/fotos/sonstiges/IMG-20240912-WA0000.jpg", description: "Der Jahresschlumpf 2024 für das Eiscafe in Ruhlsdorf ... Echte Handarbeit" },
          { src: "/fotos/sonstiges/IMG-20240912-WA0001.jpg", description: "Kleines Dankeschön an das Team in Feriendorf Dorado" },
          { src: "/fotos/sonstiges/2024_Zufalls_Treff.jpg", description: "10/2024 Zufalls-Treff" },
          { src: "/fotos/sonstiges/2025_skatrunde-scaled.jpg", description: "2025er Skatrunde Zinnowitz" },
          { src: "/fotos/sonstiges/2025_peenemuende.jpg", description: "04/2025 Besuch in Peenemünde" },
          { src: "/fotos/sonstiges/2025_veteranentreffen.jpg", description: "05/2025 Veteranentreffen in Fresendorf" },
          { src: "/fotos/sonstiges/2025_8_mai.jpg", description: "8. Mai 2025 Feiertag in Berlin" }
        
        ] }
    ]
  }
];